#
# broker.yml
#
# Simple yaml file for the env specific configuration of the broker connections.
# See the wiki for more information: http://code.google.com/p/activemessaging/wiki/Configuration
#
common: &common
  adapter: stomp
  host: 127.0.0.1
  port: 61613
  reliable: true
  reconnectDelay: 5

development:
  <<: *common

test:
  <<: *common
  adapter: test
  reliable: false

qa:
  <<: *common

qa2:
   <<: *common

staging:
  <<: *common

staging2:
   <<: *common

production:
  <<: *common

trove:
  <<: *common
