defaults: &defaults
  password_reset_email_sender: kali@intersect.org.au
  account_request_user_status_email_sender: kali@intersect.org.au
  account_request_admin_notification_sender: kali@intersect.org.au
  default_data_owner: data_owner@intersect.org.au
  licence_access_request_notification_sender: kali@intersect.org.au
  licence_access_request_response_sender: kali@intersect.org.au

development:
  <<: *defaults

test:
  <<: *defaults
  default_data_owner: data_owner@intersect.org.au

production:
  password_reset_email_sender: steve.cassidy@mq.edu.au
  account_request_user_status_email_sender: steve.cassidy@mq.edu.au
  account_request_admin_notification_sender: steve.cassidy@mq.edu.au
  default_data_owner: steve.cassidy@mq.edu.au
  licence_access_request_notification_sender: steve.cassidy@mq.edu.au
  licence_access_request_response_sender: steve.cassidy@mq.edu.au

qa:
  <<: *defaults

qa2:
  <<: *defaults

staging:
  password_reset_email_sender: jared@intersect.org.au
  account_request_user_status_email_sender: jared@intersect.org.au
  account_request_admin_notification_sender: jared@intersect.org.au
  default_data_owner: jared@intersect.org.au
  licence_access_request_notification_sender: jared@intersect.org.au
  licence_access_request_response_sender: jared@intersect.org.au

staging2:
  password_reset_email_sender: jared@intersect.org.au
  account_request_user_status_email_sender: jared@intersect.org.au
  account_request_admin_notification_sender: jared@intersect.org.au
  default_data_owner: jared@intersect.org.au
  licence_access_request_notification_sender: jared@intersect.org.au
  licence_access_request_response_sender: jared@intersect.org.au
